apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: react-app
        image: bruklemma/k8s-react:1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7800
