apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  type: NodePort
  ports:
  - port: 7800
    targetPort: 7800
    nodePort: 30000 # Optional: Specify a port in 30000–32767, or Kubernetes will assign one
    protocol: TCP
  selector:
    app: my-react-app