apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: my-react-app